# Generated by Django 2.1.7 on 2019-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledger_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='bookmarks',
            field=models.CharField(max_length=1000000000),
        ),
    ]
